void-linux/xbps

lib/package_fulldeptree.c

Otherwise we will get exponential time complexity

Don't process processed packages again in collect_rdeps

---

lib/package_remove.c

The order of entries in files.plist is inconsistent between different releases of xbps.
Hence they must be ordered before removal to, so sub directories are removed before their parents.
This solves a part of #23.

lib/package_remove: order directories before removal

---

README.md
configure
lib/Makefile
lib/portableproplib/prop_object.c
lib/util.c

This is in preparation to be compilable via tinycc.

Misc cleanups

---

lib/package_remove.c
tests/xbps/Kyuafile
tests/xbps/Makefile
tests/xbps/xbps-remove/Kyuafile
tests/xbps/xbps-remove/Makefile
tests/xbps/xbps-remove/basic_test.sh

follow up of #31 
- added test case
- fixed comparison function

package_remove: add test and fix length comparison

---

bin/xbps-fbulk/main.c

xbps-fbulk/main.c: update my email address.

---

bin/Makefile
bin/xbps-alternatives/xbps-alternatives.1
bin/xbps-checkvers/xbps-checkvers.1
bin/xbps-create/xbps-create.1
bin/xbps-dgraph/xbps-dgraph.1
bin/xbps-digest/xbps-digest.1
bin/xbps-fbulk/xbps-fbulk.1
bin/xbps-fetch/Makefile
bin/xbps-fetch/main.c
bin/xbps-fetch/xbps-fetch.1
bin/xbps-install/xbps-install.1
bin/xbps-pkgdb/xbps-pkgdb.1
bin/xbps-query/xbps-query.1
bin/xbps-reconfigure/xbps-reconfigure.1
bin/xbps-remove/xbps-remove.1
bin/xbps-rindex/xbps-rindex.1
bin/xbps-uchroot/xbps-uchroot.1
bin/xbps-uhelper/main.c
bin/xbps-uunshare/xbps-uunshare.1
data/xbps.d.5

xbps-install(1): document all libfetch env vars.

xbps-fetch(1): new utility that replaces 'xbps-uhelper fetch'.

---

include/xbps.h.in
lib/repo.c
lib/rpool.c

https://github.com/void-linux/xbps/issues/3

lib/repo: add xbps_repo_remove and use it in xbps_rpool_foreach

---

bin/xbps-checkvers/main.c
bin/xbps-dgraph/main.c
bin/xbps-install/main.c
bin/xbps-pkgdb/check_pkg_alternatives.c
bin/xbps-rindex/repoflush.c
lib/Makefile
lib/external/fexec.c
lib/fetch/common.c
lib/initend.c
lib/portableproplib/rb.c
lib/repo.c
lib/transaction_dictionary.c
lib/transaction_ops.c
lib/util.c

Fixes found by clang-analyzer.
Still in progress

clang analyzer fixes

---

bin/xbps-uchroot/main.c
bin/xbps-uchroot/xbps-uchroot.1
bin/xbps-uunshare/main.c
bin/xbps-uunshare/xbps-uunshare.1

Provides an alternative for #177

uunshare: document -- usage as end-of-options

---

bin/xbps-install/transaction.c

Lovely codebase.
This PR is for issue #157 .
Simply, checks if all packages are on hold and exits if so. This happens immediately before the [Y/n] prompt appears, so after the actions/sizes are shown. I think this is more appropriate than before the actions/sizes are shown.

xbps-install: early exit when all packages on hold (no prompt)

---

lib/transaction_prepare.c

If all packages in transaction are on hold, there's no
need to check for conflicts, shlibs, etc.
This makes `xbps-install -un` work faster on my system:
~450ms -> ~250ms
There's still room for more improvements :-)
#168

xbps_transaction_prepare: optimize a bit.

---

bin/xbps-create/main.c
tests/xbps/xbps-create/basic_test.sh

Added a new test case.
Close #199

xbps-create: always sanitize gathered symlinks.

---

bin/xbps-checkvers/main.c
bin/xbps-checkvers/xbps-checkvers.1
tests/xbps/xbps-checkvers/checkvers_test.sh

bin/xbps-checkvers: list removed templates

---

tests/xbps/xbps-alternatives/main_test.sh

This bug was triggered by removing the cc alternative group from gcc and clang.
I forgot to this variant with the latest xbps.

add test which replaces an alternative group with a symlink

---

bin/xbps-install/main.c
bin/xbps-install/xbps-install.1

* man page was flat out wrong
* usage string was inconsistent with the rest

xbps-install -R docs fixed

---

data/_xbps_src

See-also: https://github.com/void-linux/void-packages/pull/19927

zsh-completion: xbps-src: complete -q

---

README.md

https://en.wikipedia.org/wiki/Inequality_(mathematics)

fixed a grammatical error in the README

---

bin/xbps-install/transaction.c

xbps-install: fflush before asking for confirmation

---

README.md

Added forgotten option dash for **README.md**

fix minor mistake in README

---

README.md

LGTM is now CodeQL and Travis hasn't been in use for a while now

README.md: update status badges

---

bin/xbps-alternatives/main.c
bin/xbps-checkvers/main.c
bin/xbps-digest/main.c
bin/xbps-fbulk/main.c
bin/xbps-fetch/main.c
bin/xbps-install/main.c
bin/xbps-install/transaction.c
bin/xbps-pkgdb/check.c
bin/xbps-pkgdb/main.c
bin/xbps-query/search.c
bin/xbps-query/show-info-files.c
bin/xbps-remove/main.c
bin/xbps-rindex/index-add.c
bin/xbps-rindex/index-clean.c
bin/xbps-rindex/main.c
bin/xbps-rindex/remove-obsoletes.c
bin/xbps-rindex/sign.c
bin/xbps-uchroot/main.c
bin/xbps-uhelper/main.c
tests/xbps/xbps-fetch/fetch_test.sh

this should unify the format of most of the error messages xbps gives

bin/: use xbps logging functions more

---

bin/xbps-create/xbps-create.1

for #538
alpha order used: shortopts (upper before lower for each letter), then longopts

bin/xbps-create/xbps-create.1: add --sourcepkg, alphabetise

---

bin/xbps-remove/clean-cache.c
bin/xbps-remove/defs.h
bin/xbps-remove/main.c
bin/xbps-remove/xbps-remove.1
tests/xbps/xbps-remove/basic_test.sh

Change "obsolete packages" to "outdated packages" when describing the old behaviour.

bin/xbps-remove: allow removing uninstalled packages from the cache
