void-linux/xbps

bin/xbps-create/main.c
lib/package_unpack.c

Fixes building on 32-bit systems (prior to GCC 7.x?)
Based on patch by @pbui from the previous repository: voidlinux/xbps#287

Fix string formatting of 64-bit unsigned integers

---

bin/xbps-alternatives/main.c
bin/xbps-create/main.c
bin/xbps-install/main.c
bin/xbps-install/state_cb.c
bin/xbps-pkgdb/check.c
bin/xbps-pkgdb/check_pkg_unneeded.c
bin/xbps-query/list.c
bin/xbps-query/ownedby.c
bin/xbps-query/search.c
bin/xbps-reconfigure/main.c
bin/xbps-remove/clean-cache.c
bin/xbps-remove/main.c
bin/xbps-rindex/index-clean.c
bin/xbps-rindex/remove-obsoletes.c
bin/xbps-uchroot/main.c
configure
lib/package_orphans.c
lib/plist_fetch.c
lib/rpool.c
lib/transaction_conflicts.c

Fixes building on PowerPC systems (depends on header files that conflict with _unused).
Based on patch by @ncopa from the previous repository: voidlinux/xbps#292

Fix namespace violation

---

configure
lib/fetch/common.c
lib/pubkey2fp.c

Maybe people are right. Openssl do make their bad API worse.
But still we need to live with it.
Lot of distro have been upgraded to openssl 1.1.x.
It is better to support 1.1.x and drop 1.0.x support. (Or add some FENCE to make both work?)
May somebody help and pick the modification and make xbps works for 1.1.x?

Maybe we need upgrade to openssl 1.1.x.

---

data/_xbps
data/_xbps_src

We recently added the ppc64 target, so add that to completions now. Also add the 32-bit ppc ones, which have been in tree for a while.

data/_xbps,_xbps_src: add ppc64+ppc(-musl) completions

---

COPYING
lib/transaction_ops.c
tests/xbps/libxbps/shell/install_test.sh

This fixes the cases where a pkg installation or update
could break its revdeps due to not satisfying dependencies.
When performing an install or update, xbps now always checks if
there are updates for its revdeps and get added to the transaction.
See the two new test cases for more information.

Update revdeps when installing or updating pkgs

---

lib/package_fulldeptree.c

They most likely come from `ignorepkg` and without this patch
operations xbps-remove -R aborts if a dependency was ignored
at install time.

fulldeptree: ignore missing local runtime dependencies

---

bin/xbps-install/question.c

this fixes a bug:
1. ```sh
mkdir test
xbps-install -S -R https://alpha.de.repo.voidlinux.org/current -r test base-system
```
2. when it asks if you want to import the rsa key, type `y` and press enter
3. notice how it assumes yes when it asks if you want to install the packages
step 2 only reads the "y" character from stdin, so in step 3 it gets the newline and assumes the default answer

xbps-install: make question() read the whole input line

---

lib/package_remove.c
lib/util.c
tests/xbps/libxbps/shell/remove_test.sh

This fixes removal of packages that contain multiple levels
of dangling symlinks, i.e faenza-icon-theme and probably others.
Close #23

libxbps: remove dangling symlinks properly.

---

configure
lib/package_alternatives.c
tests/xbps/xbps-alternatives/main.sh

xbps alternatives: multiple fixes, new test cases.

---

.gitignore
bin/Makefile
bin/xbps-alternatives/xbps-alternatives.1
bin/xbps-checkvers/xbps-checkvers.1
bin/xbps-create/xbps-create.1
bin/xbps-dgraph/xbps-dgraph.1
bin/xbps-digest/Makefile
bin/xbps-digest/main.c
bin/xbps-digest/xbps-digest.1
bin/xbps-fbulk/xbps-fbulk.1
bin/xbps-install/xbps-install.1
bin/xbps-pkgdb/xbps-pkgdb.1
bin/xbps-query/xbps-query.1
bin/xbps-reconfigure/xbps-reconfigure.1
bin/xbps-remove/xbps-remove.1
bin/xbps-rindex/xbps-rindex.1
bin/xbps-uchroot/xbps-uchroot.1
bin/xbps-uhelper/main.c
bin/xbps-uunshare/xbps-uunshare.1
data/xbps.d.5

See the manual page:
XBPS-DIGEST(1)              General Commands Manual             XBPS-DIGEST(1)
NAME
xbps-digest - XBPS utility to generate message digests
SYNOPSIS
xbps-digest [OPTIONS] [FILE] [FILE+N]
DESCRIPTION
The xbps-digest utility generates message digests for specified FILE or
stdin if unset.
OPTIONS
-m, --mode mode
Sets the message digest mode. Supported: sha256.  If unset, defaults
to sha256.
-h, --help
Show the help message.
-V, --version
Show the version information.
SEE ALSO
xbps.d(5), xbps-checkvers(1), xbps-create(1), xbps-dgraph(1),
xbps-fbulk(1), xbps-install(1), xbps-pkgdb(1), xbps-query(1),
xbps-reconfigure(1), xbps-remove(1), xbps-rindex(1), xbps-uchroot(1),
xbps-uunshare(1)
AUTHORS
Juan Romero Pardines <xtraeme@gmail.com>
BUGS
Probably, but I try to make this not …

xbps-digest(1): new utility that replaces "xbps-uhelper digest".

---

configure

Why? because the code intentionally uses assert(), and we want the code
to always run as was designed.

configure: remove `--enable-debug`.

---

lib/transaction_ops.c
tests/xbps/libxbps/shell/update_itself.sh

The current code was failing because while checking for updates
on its reverse dependencies, up-to-date versions were treated
as an error.
Added a new test case to verify that it works as expected.

libxbps: fix xbps autoupdate when its revdeps are up-to-date.

---

lib/pkgdb.c

As shown in https://github.com/void-linux/xbps/issues/110
/var might be rw, while / might be ro.
Check this via xbps_pkgdb_lock() for both things.
Close #110

xbps_pkgdb_lock(): check if rootfs is writable.

---

lib/util.c

Before and after:
```
$ strace -e access xbps-install -un
access("/var/cache/xbps/go-1.12.6_1.x86_64.xbps", R_OK) = -1 ENOENT (No such file or directory)
access("https://alpha.de.repo.voidlinux.org/current/go-1.12.6_1.x86_64.xbps", R_OK) = -1 ENOENT (No such file or directory)
access("/var/cache/xbps/isync-1.3.1_2.x86_64.xbps", R_OK) = -1 ENOENT (No such file or directory)
access("https://alpha.de.repo.voidlinux.org/current/isync-1.3.1_2.x86_64.xbps", R_OK) = -1 ENOENT (No such file or directory)
access("/var/cache/xbps/mupdf-1.15.0_3.x86_64.xbps", R_OK) = -1 ENOENT (No such file or directory)
access("https://alpha.de.repo.voidlinux.org/current/mupdf-1.15.0_3.x86_64.xbps", R_OK) = -1 ENOENT (No such file or directory)
access("/var/cache/xbps/nginx-1.16.0_2.x86_64.xbps", R_OK) = -1 ENOENT …
```

xbps_binpkg_exists: fix access() on remote packages and avoid malloc

---

bin/xbps-dgraph/main.c
bin/xbps-query/show-deps.c
lib/package_fulldeptree.c
lib/package_orphans.c
tests/xbps/libxbps/shell/incorrect_deps_test.sh

xbps_get_pkg_fulldeptree() now returns NULL and sets errno to ENODEV
when there are missing dependencies, rather than assert()ing.
Added another test case to check returned error codes.

fulldeptree: return a proper error if deps can't be resolved.

---

bin/xbps-checkvers/main.c
bin/xbps-checkvers/xbps-checkvers.1
tests/xbps/xbps-checkvers/checkvers.sh

from the man page:
```
-f, --format format
Format according to the string format, inspired by printf(3).
The following formatting codes may be used:
\n      Newline.
\t      Tab.
\0      NULL.
%%      A plain ‘%’.
%n      The package name.
%r      The repository version.
%s      The source package version.
The default format is “%n %r %s”.
```
The other commit makes it easier to just pass a list of package names, instead of having to construct paths.

xbps-checkvers --format

---

NEWS
README.md
bin/xbps-rindex/main.c
bin/xbps-rindex/repoflush.c
bin/xbps-rindex/xbps-rindex.1

Any compression format from that list is supported without
additional changes: gzip, bzip2, lz4, xz, zstd.
This is for repository data and binary packages.
Close #122

xbps: restore default repodata compression format (gzip/zlib).

---

lib/transaction_files.c
tests/xbps/libxbps/shell/obsoletefiles_test.sh

Test case 1. where a directory with preserved files is changed to another file type, will abort before transaction.
Test case 2. where a preserved symlink is replaced with a file, will just skip considering it obsolete and leave it as it is.

Obsoletes preserve

---

lib/package_unpack.c

On some systems, something like this happens:
```
package_unpack.c: In function 'xbps_unpack_binary_pkg':
package_unpack.c:375:11: error: 'buf' may be used uninitialized in this function [-Werror=maybe-uninitialized]
rv = xbps_file_hash_check_dictionary(
^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
xhp, binpkg_filesd, "files", buf);
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
package_unpack.c:87:18: note: 'buf' was declared here
char *pkgname, *buf;
^~~
cc1: all warnings being treated as errors
make[1]: *** [Makefile:74: package_unpack.o] Error 1
make[1]: *** Waiting for unfinished jobs....
make[1]: Leaving directory '/builddir/xbps-0.54/lib'
make: *** [Makefile:15: all] Error 1
=> ERROR: xbps-0.54_1: do_build: '${make_cmd} ${makejobs} ${make_build_args} ${make_build_target}' exited with 2
=> ERROR:   in …
```

lib/package_unpack.c: silence gcc false positive

---

NEWS
bin/xbps-install/main.c
bin/xbps-install/xbps-install.1
include/xbps.h.in
lib/transaction_files.c
tests/xbps/libxbps/shell/obsoletefiles_test.sh

If set it will continue with the transaction and will
just print what are the conflicting files without returning
EEXIST.
This is a temporary solution for void where there are still
some packages with conflicting files (qt5-host-tools vs qt5-tools-devel).
With input by @duncaen

xbps-install(1): added -I, --ignore-file-conflicts.

---

lib/plist.c

the first thread to finish will start again from 0 (reserved) until 0+slicecount,
next thread will then start from the end of the previous thread which
is already wrong, resulting in processing the first slicecount*maxthreads
entries twice.
The first slicecount*maxthreads entries are accounted by the thread
creation loop and `reserved` has to start at the first unaccounted index.

lib/plist.c: fix xbps_array_foreach_cb_multi processing entries multiple times

---

lib/transaction_revdeps.c
tests/xbps/libxbps/shell/ignore_test.sh

At the moment `ignorepkg` only works on install and update, this change allows users to add a package to the ignored packages after installation and then remove the package with `xbps-remove`.

ignorepkg removal

---

bin/xbps-install/transaction.c

makes 58509996aabea52ffc40e5e01c9eb00730c6cdcc work for
`xbps-install -u <pkg>`

bin/xbps-install: update_pkg return EEXIST if package is up to date

---

lib/package_fulldeptree.c
lib/package_orphans.c
tests/xbps/libxbps/find_pkg_orphans/main.c
tests/xbps/libxbps/find_pkg_orphans/pkgdb-0.38.plist
tests/xbps/libxbps/shell/incorrect_deps_test.sh

This fixes and adds a test case for an issue we are currently experiencing, where orphaned are not correctly removed, if there are more than one package depending on the same package.
The main issue is that `xbps_get_pkg_fulldeptree` only finds each dep it encounters once, adding the deps to the hashtable, but then never again adding them to any results.
So if `xbps_get_pkg_fulldeptree` is called multiple times and the requested packages share dependencies in their fulldeptree, there are going to be packages missing from the results array.
Another small thing I fixed is to not add the requested package itself to the results:
```
$ xbps-query --fulldeptree -Rx linux4.19
linux4.19-4.19.56_1
```

Fulldeptree fixups

---

include/xbps_api_impl.h
lib/transaction_ops.c
lib/transaction_prepare.c
lib/transaction_revdeps.c
tests/xbps/libxbps/shell/install_test.sh

This patchset removes revdep updates from `xbps_transaction_update_pkg` and `xbps_transaction_install_pkg` and uses the `xbps_transaction_revdeps` function to add required revdep updates to the transaction.
This will make xbps only update revdeps on install/update if the update is really required.
From commit message:
`xbps_transaction_revdeps` will now try to add updates for packages to the
transaction if the dependency is not satisified anymore due to a package
install/update.
`xbps_transaction_prepare` will now check the return value of
`xbps_transaction_revdeps` and repeat the dependency resolution,
until `xbps_transaction_revdeps` returns 0, which means that it didn't
add any new packages to the transaction.

smart revdep updates

---

NEWS
bin/xbps-checkvers/main.c
include/xbps_api_impl.h
lib/conf.c
lib/package_remove.c
lib/transaction_files.c
lib/transaction_ops.c
lib/transaction_prepare.c
lib/transaction_revdeps.c
tests/xbps/libxbps/shell/install_test.sh
tests/xbps/libxbps/shell/obsoletefiles_test.sh
tests/xbps/libxbps/shell/remove_test.sh

This reverts some changes, I'm not really sure about because they influence the installation order of found reverse dependencies and might be slow in certain cases.
The biggest change is that the transaction file checks are used for package removal, this fixes removing wrong files and removes a lot of duplicated code.
Another big reason to get this release out, is fixing obsoletes removal.
I plan to add the other 3 issues from the milestone to this PR:
https://github.com/void-linux/xbps/milestone/2
Some other patches are minor and/or were already added to the live version.

Prepare 0.57

---

bin/xbps-create/main.c
bin/xbps-rindex/repoflush.c
lib/archive.c

This resolves the issues we've seen when `/hostdir` is full.
1. `xbps-rindex` would overwrite repodata with an empty file if some of the writes fail, in our case we lost some staged packages from the index. 
1. `xbps-create` would create incomplete archives that can't be added to the repository index and would also make `xbps-src` skip registering a new build until all corrupt `.xbps` files were removed manually.

Archive write errors

---

lib/package_alternatives.c
tests/xbps/xbps-alternatives/main_test.sh

In the edge case when an updated package has different (or no) alternatives groups, make sure to prune those that are in pkgdb but not in the newly installed package.
A potentially common case of this is when a package that formerly had alternatives gets removed and a transitional metapackage takes its place (which has no alternatives).
I ran across this when updating `openjdk` and renaming it to `openjdk8` and adding transitional packages. I don't think it can be updated before a fix for this is in xbps, either this one or something better...

lib/package_alternatives.c: prune obsolete alternatives groups

---

bin/xbps-checkvers/main.c
tests/xbps/xbps-checkvers/checkvers_test.sh

Up until now `xbps-checkvers` would only check for the
real sourcepkg, this broke detection of binary packages
that are subpkgs.
Added a new test case.
Close #192

xbps-checkvers: use binpkg's pkgname rather than srcpkgs.

---

lib/initend.c
tests/xbps/libxbps/shell/scripts_test.sh
tests/xbps/xbps-uhelper/arch_test.sh

This way we don't need to set the 'architecture' xbps.d
setting when the binaries are compiled for musl.
Close #195

xbps_init: autodetect musl libc variant at compile time.

---

lib/transaction_conflicts.c
tests/xbps/libxbps/shell/conflicts_test.sh

See the new test case for details, but this simulates
the recent glvnd switch, with mesa, nvidia and libglvnd.
Thanks @st3r4g for the fix! this indeed fixes the new test case.
Close #186

libxbps: fix issue found by the recent glvnd switch.

---

bin/xbps-install/transaction.c
include/xbps.h.in
lib/transaction_ops.c
tests/xbps/libxbps/shell/install_test.sh
tests/xbps/libxbps/shell/update_itself_test.sh

When there's a new xbps update, xbps-install(1) will now return
EBUSY (16) and a message (if dry-run disabled) explaining
how to proceed.
If there's an update and transaction does not contain xbps, it will
error out unless the 'xbps' pkg is the only target pkg, i.e:
```
The 'xbps' package must be updated, please run `xbps-install -u xbps`
16
```
To update xbps, the only way to proceed is to explicitly declare
it as an update, i.e:
```
```
The dry-run mode will still show there's an xbps update.
Modified the existing test cases to satisfy the new behaviour.
Closes #166
Closes #142

Do not silently update xbps on any install/update transaction.

---

lib/verifysig.c

Only read keys from dedicated directory.

Revert "libxbps: verify repodata signatures even if rootdir is unset."

---

bin/xbps-fetch/main.c
bin/xbps-fetch/xbps-fetch.1
lib/download.c

First commit fixes the checksum output if a download was continued.
Second commit adds a checksum output to `xbps-fetch(1)`, I mainly did this to easily test the fix but I think this could be useful for xbps-src because large downloads can be fetched and the checksum generated at the same time.

Fix digest

---

data/xbps.conf
data/xbps.d.5
include/xbps.h.in
lib/conf.c
lib/initend.c
lib/package_config_files.c
tests/xbps/libxbps/shell/conf_files_test.sh

Add configuration option keepconf that stops xbps from overwriting
unchanged configuration files. If keepconf=true, xbps will store the new
configuration as <name>.new-<version> instead of overwriting unchanged
configuration files.
On production servers which I take care of, there are a number of different programs using default configuration. When upgrading, xbps normally overwrites an unchanged configuration with new defaults. This can lead to the server behaving unexpectedly. This is an RFC/PoC for adding a configuration knob that allows preventing xbps from overwriting default configuration, giving the user complete control.
Is this a good idea?

RFC: configuration: add keepconf option

---

bin/xbps-uchroot/main.c

- Do not use nftw(3), this won't clean up the tree properly.
Rather use scandir(3) with alphasort, like xbps-create(1).
- Don't drop privs in the parent to make sure that the
temp overlayfs tree can be removed properly.
This fixes the issues while building go modules and others
with xbps-src.

xbps-uchroot: overlayfs fixes v2.

---

lib/transaction_store.c
tests/xbps/libxbps/shell/incorrect_deps_test.sh

This change ensures that no multiple versions of the same pkg
are added to the transaction; if a new version of the same
package is being added as a dependency, compare stored
and current and use the greatest one.
This fixes the recent issue seen in the aarch64 builders, where
two versions of the same package were added to the transaction.
Added a new test case.

xbps_transaction_store: ensure no multiple versions.

---

bin/xbps-install/state_cb.c
bin/xbps-install/transaction.c
bin/xbps-install/util.c
include/xbps.h.in
include/xbps_api_impl.h
lib/Makefile
lib/package_alternatives.c
lib/package_fulldeptree.c
lib/package_orphans.c
lib/package_register.c
lib/package_unpack.c
lib/pkgdb.c
lib/plist.c
lib/plist_find.c
lib/repo.c
lib/transaction_check_conflicts.c
lib/transaction_check_replaces.c
lib/transaction_check_revdeps.c
lib/transaction_check_shlibs.c
lib/transaction_commit.c
lib/transaction_fetch.c
lib/transaction_files.c
lib/transaction_ops.c
lib/transaction_pkg_deps.c
lib/transaction_prepare.c
lib/transaction_store.c
tests/xbps/libxbps/shell/hold_test.sh
tests/xbps/libxbps/shell/update_hold_test.sh

This commit implements multiple performance improvements
to the transaction code:
- Don't process xbps_pkg_name() N times each time we access
its package dictionary (via pkgdb or rpool), just do it once
at xbps_pkgdb_init() time. At pkgdb init time, it just creates
a property in pkgdb, "pkgname". At rpool time, each time a
package is accessed, the "pkgname" string property is added.
- The package transaction dictionary contains the "transaction"
object to know what's the pkg type. This has been changed to an
uint8, this simplifies the logic and it's faster than checking
a string object. See xbps_trans_type_t and xbps_transaction_pkg_type().
- Fixed the issue that was marked with XXX in transaction shlibs
checking code. This has been fixed and improved and resources are
now just freed as …

xbps_transaction_*: multiple performance improvements (v2).

---

lib/transaction_prepare.c

- if pkg trans type is UPDATE or REMOVE, don't set
download stats, we don't need them.
- Simplify code.

xbps_transaction_prepare: set transd stats correctly.

---

lib/package_orphans.c

Make sure "automatic" bool is initialized to false before
checking its value. This way if xbps_dictionary_get_bool()
fails, "automatic" will be set to false.
Closes #234

xbps_find_pkg_orphans: fix for #234

---

README.md
bin/xbps-create/main.c
bin/xbps-create/xbps-create.1
bin/xbps-rindex/main.c
bin/xbps-rindex/repoflush.c
bin/xbps-rindex/xbps-rindex.1

There's lots of benchmarks right there, zlib vs zstd, xz vs zstd.
Take your own conclusion.

xbps-{create,rindex}: use zstd by default.

---

bin/xbps-install/defs.h
bin/xbps-install/transaction.c
bin/xbps-install/util.c
bin/xbps-query/list.c

To make sure we don't get a negative value due to overflowing.

bin: use size_t where applicable.

---

bin/xbps-fetch/xbps-fetch.1
lib/fetch/common.c

Allows to [configure CI job](https://github.com/Chocimier/void-packages-org/commit/a09733b7748ede191a4cbf44bc447952d96bdf63) to build from ftp source without taking too much time as [demostrated with chrootkit](https://travis-ci.org/Chocimier/void-packages-org/builds/647493514).

xbps-fetch: TIMEOUT_CONNECTION to customize time waiting for response

---

.travis.yml

Change the build environment from the current travis default (xenial) to
bonic, so that we can run on a newer kernel. This gets rid of issues
related with coreutils due to the statx syscall which is unavailable on
xenial kernels.

travis: build on bionic

---

bin/xbps-fbulk/main.c
bin/xbps-fbulk/xbps-fbulk.1

xbps-fbulk: parallel working implementation.
- Removed -a, this won't work due to dependency cycles between host/target.
- Do the process in two steps: collect deps and then build.
- Cleaned up the whole code.
Running for some days already with no issues, works reliably.

xbps-fbulk v2

---

bin/xbps-uchroot/main.c
bin/xbps-uchroot/xbps-uchroot.1

- Added -B src:dest (like -b) but this makes bind mounts in
read-only mode.
- Get rid of setfsuid(), it's unnecessary.
- Make sure chrootdir is not '/', use realpath().
- Always set SECBIT_NOROOT, see capabilities(7).
- Do not mount recursively, right now this only mounts
/dev (ro), /dev/shm (rw), /sys (ro) and /proc (ro).
Previously any mount below any specific mount were recursively
mounted in chrootdir.

xbps-uchroot: support read-only bind mounts, misc improvements.

---

bin/xbps-query/list.c
bin/xbps-query/search.c
bin/xbps-query/show-deps.c

This should also fix a useless error from lgtm

bin/xbps-query: simplify search result printing (with truncation)

---

lib/package_register.c
tests/xbps/libxbps/shell/hold_test.sh

I noticed that while updating a pkg that is on hold
or in repolock mode, does not keep those properties.
Always set those props in the new pkg dictionary to respect
this behaviour. If there's a pkg on hold and you update it,
you want to keep it in this state unless you tell it to change.
Added new test case to verify.

xbps_register_pkg: keep stored props in pkgdb on updates.

---

lib/transaction_files.c
tests/xbps/libxbps/shell/obsoletefiles_test.sh

Deleting obsolete directories is different from deleting obsolete files,
files need to be deleted by the first package that might change the file
into a different file type.
Directories need to be deleted by the last package that removes files
out of the directory to avoid ENOTEMPTY if another package has a file in
the given directory which is uninstalled later.
This fixes #282.

lib/transaction_files.c: fix leaving behind obsolete directories

---

bin/xbps-install/xbps-install.1

It is a common confusion that --yes should also accept new signing keys;
it really shouldn't, so document that explicitly. Also explain how to
tell XBPS about trusted keys.

xbps-install.1: improve description for -y.

---

data/xbps.conf
data/xbps.d.5

keepconf is a boring option and is not needed in most situations. Make
this more clear in the documentation, e.g. that it only affects
*unchanged* configuration files, and that changed configuration files
are unaffected by this option.

docs: Improve description of keepconf option

---

lib/fetch/http.c

With HTTP 1.1 persistent connection is default and Connection
header is not sent.
Before patch, for every file, including 512b signature, there was
done dns query, tls handshake etc.

lib/fetch: reuse http connection

---

.github/codeql/codeql-config.yaml
.github/workflows/ci.yaml
.github/workflows/codeql.yaml

As of today, LGTM will [no longer be reviewing pull requests](https://github.blog/2022-08-15-the-next-step-for-lgtm-com-github-code-scanning/), and will shut down fully on 16 December. Github now runs the same service built-in as CodeQL, and integrates it into the [security tab](https://github.com/void-linux/xbps/security) of the repo.
I've replicated the LGTM setup to the best of my knowledge.
cc: @void-linux/xbps-developers 
(also includes a couple improvements to the build/test workflow I noticed)

CI: migrate from LGTM to Github CodeQL

---

bin/xbps-rindex/remove-obsoletes.c

If `repodir` is given as a relative path, it will not work because it will try to open the dir relative to itself because it already `chdir()`ed into `repodir`. This fixes `xbps-rindex -r` when relative paths are specified.
fixes #519

bin/xbps-rindex/remove-obsoletes.c: always `opendir()` pwd

---

include/xbps.h.in

While reading `xbps-install(1)`'s source i noticed that these two return values of `xbps_transaction_update_packages(3)`'s doc weren't documented.

libxbps: Update xbps_transaction_update_packages(3) doc

---

bin/xbps-reconfigure/Makefile
bin/xbps-reconfigure/defs.h
bin/xbps-reconfigure/find-deps.c
bin/xbps-reconfigure/main.c
bin/xbps-reconfigure/xbps-reconfigure.1

adds `-x/--deps` and `--fulldeptree`, that behave similar to the xbps-query modes
fixes #464
```
$ doas bin/xbps-reconfigure/xbps-reconfigure -fx linux  
linux5.15: configuring ...
Executing post-install kernel hook: 20-dracut ...
dracut: dracut module 'cifs' depends on 'network', which can't be installed
Mode:           real
Files:          2593
Linked:         221 files
Compared:       0 xattrs
Compared:       3866 files
Saved:          17.58 MiB
Duration:       0.030899 seconds
Executing post-install kernel hook: 50-efibootmgr ...
Executing post-install kernel hook: 50-grub ...
Generating grub configuration file ...
Found background: /usr/share/void-artwork/splash.png
Found linux image: /boot/vmlinuz-5.15.34_1
Found initrd image: /boot/initramfs-5.15.34_1.img
Found linux image: …
```

xbps-reconfigure: add ability to reconfigure dependencies

---

lib/repo.c

Instead of just cryptically exiting 0 when opening a non-existant repodata or stagedata, with the only message existing in the debug output, show an error to the user on stderr.
mentioned in #519

lib/repo.c: add user-facing error message when repodata doesn't exist

---

bin/xbps-alternatives/xbps-alternatives.1
bin/xbps-checkvers/xbps-checkvers.1
bin/xbps-create/xbps-create.1
bin/xbps-dgraph/xbps-dgraph.1
bin/xbps-digest/xbps-digest.1
bin/xbps-fbulk/xbps-fbulk.1
bin/xbps-fetch/xbps-fetch.1
bin/xbps-install/xbps-install.1
bin/xbps-pkgdb/xbps-pkgdb.1
bin/xbps-query/xbps-query.1
bin/xbps-reconfigure/xbps-reconfigure.1
bin/xbps-remove/xbps-remove.1
bin/xbps-rindex/xbps-rindex.1
bin/xbps-uchroot/xbps-uchroot.1
bin/xbps-uunshare/xbps-uunshare.1
data/xbps.d.5

- use `.Os` to show "Void Linux" in the footer
- use `Aq Mt` to display email addresses
- use `.Lk` for the bug link
- remove unnecessary use of `.Nm <name>` when already defined
- add xbps-alternatives(1) to SEE ALSO where missing
- bump date

manpages: small formatting improvements

---

bin/xbps-uhelper/main.c

- allow multiple arguments for many actions
Only implemented where it makes sense to, i.e., not `cmpver`, `pkgmatch`, `arch`, `getsystemdir`, `digest`, and `fetch`.
Tests show a large speed-up is possible when processing a large number of inputs (1718 in this case):
**Before**
```
xbps-query -Rp pkgver -s python  0.18s user 0.02s system 99% cpu 0.199 total
cut -d: -f1  0.00s user 0.00s system 0% cpu 0.198 total
xargs -n1 xbps-uhelper getpkgname > /dev/null  0.49s user 1.17s system 94% cpu 1.761 total
```
**After**
```
xbps-query -Rp pkgver -s python  0.17s user 0.03s system 99% cpu 0.200 total
cut -d: -f1  0.00s user 0.00s system 0% cpu 0.200 total
xargs ./bin/xbps-uhelper/xbps-uhelper getpkgname > /dev/null  0.00s user 0.00s system 1% cpu 0.197 total
```
(note the lack of `-n1` in the …

bin/xbps-uhelper: allow multiple arguments for many actions

---

bin/xbps-uhelper/Makefile
bin/xbps-uhelper/main.c
bin/xbps-uhelper/xbps-uhelper.1
data/_xbps

- bin/xbps-uhelper: add longopts for -CdrV
- bin/xbps-uhelper: add manpage
- data/_xbps: add xbps-uhelper getname, getversion to completions
I started (and mostly finished) this manpage before looking at the open PRs and seeing #305, and seeing as that PR has sat for a year and a half now, I'm submitting my alternative take on the uhelper manpage.
It's mostly the same, with some minor formatting differences, and a couple additional sections.
I did not include `xbps-uhelper fetch` and `xbps-uhelper digest` in the manpage because they are replaced by `xbps-fetch` and `xbps-digest` (https://github.com/void-linux/xbps/blob/master/NEWS#L357-L359).
closes #305

bin/xbps-uhelper: add longopts, manpage

---

bin/xbps-create/main.c

This can be used similar to source-revisions, it should be set to the pkgver of the template. This then allows to find removed subpackages by looking for packages with outdated sourcepkg versions.

bin/xbps-create: add sourcepkg metadata variable

---

bin/xbps-pkgdb/check.c
bin/xbps-pkgdb/main.c
lib/fetch/http.c

Use -errno values for error states when checking a package. This will give more relevant information than before, removes a message that is misleading in many cases, and allows for some minor simplification.
before:
```
$ doas xbps-pkgdb runit-void; echo $?
ERROR: runit-void: hash mismatch for /etc/runit/2.
ERROR: runit-void: files check FAILED.
Failed to check `runit-void': Operation not permitted
1
```
after:
```
$ doas xbps-pkgdb runit-void; echo $?
ERROR: runit-void: hash mismatch for /etc/runit/2.
ERROR: runit-void: files check FAILED.
1
```
this does not change the behaviour of `xbps-pkgdb -a`.
---
second commit is an unrelated change, but this is the first time CI has been run on clang 15 so it was caught there.

bin/xbps-pkgdb: use -errno values for error states

---

bin/xbps-remove/clean-cache.c
bin/xbps-rindex/remove-obsoletes.c
bin/xbps-rindex/sign.c
configure
include/xbps.h.in
lib/transaction_fetch.c
lib/util.c
lib/verifysig.c

Since 8d5c48b, xbps has used a sha1 ASN1 prefix with a sha256 hash, and as of openssl v3, openssl cares about this. This works around that in a compatible way by moving to a second sig file, `binpkg.sig2`.
For `xbps-remove -O` and `xbps-rindex -r`, also clean up obselete `.sig` files.
- `xbps-rindex -S` of a package to generate a `.sig2`
- `xbps-rindex -r` of a package with both `.sig` and `.sig2`
- `xbps-remove -O` of a package with both `.sig` and `.sig2` in cache
- `xbps-install` of a package with a `.sig2`
- upgrade of xbps with this patch applied works (requires a couple minor changes to rebase and apply cleanly on 0.59.1)
- upgrading openssl to v3 and using xbps with it (see [this branch](https://github.com/void-linux/void-packages/compare/master...classabbyamp:void-packages:xbps-sig …

lib/, bin/: fix signature type, now called *.sig2

---

README.md
data/repod-main.conf
data/xbps.conf
data/xbps.d.5

- README.md: fix static binary urls, replace mips with armv7
- data/: update listed mirror urls
should maybe remove these from the mirrors:
```
xbps-static-latest.mips-musl.tar.xz                26-Sep-2021 02:55             2324644
xbps-static-latest.mipsel-musl.tar.xz              26-Sep-2021 02:55             2454672
```

README.md: fix static binary urls, replace mips with armv7

---

.github/workflows/codeql.yaml
bin/xbps-dgraph/main.c

bin/xbps-dgraph: print usage if package is not given

---

bin/xbps-fbulk/main.c

This fixes a warning on gcc14 (compile failure with werror).
This was fixed in the master branch with https://github.com/void-linux/xbps/commit/4f8e07aa64c329d6a134af373edc45d2a4c8d9e1 and later changed to just a malloc in https://github.com/void-linux/xbps/commit/da2c104d1642611c6491bd4b1771de8524bf7731, but this was never backported to the 0.59.x branch.
I'm just leaving it as a calloc to not break stuff, if you want it to become a malloc, let me know.

bin/xbps-fbulk: fix transposed calloc args

---

lib/fetch/fetch.c

This prevents the tilde (`~`) character from being escaped as `%7e` in paths.
For example, this URL didn't previously resolve correctly...
```
http://www.cs.columbia.edu/~lennox/udptunnel/udptunnel-1.1.tar.gz
```
Fixes #606

xbps-fetch: don't url-escape tilde character in path

---

bin/xbps-query/main.c
bin/xbps-query/xbps-query.1
data/_xbps

makes the behaviour of the `-R`/`--repository` flags match what xbps-install et al. do, namely `-R <repo>` and `--repository <repo>` now work. Existing behaviours are preserved.
allows `PKG` argument to appear anywhere in `argv` for more flexible argument parsing. This is now a valid command, for example:
```
xbps-query -Rx --fulldeptree foo
```
This also improves some error messages instead of just printing the `usage()` naïvely.

bin/xbps-query: improve argument parsing

---

bin/xbps-install/transaction.c

this ensures there will always be 6 fields per line, making it possible to parse the output consistently. `arch` and `repository` default to `-`. `installed_size` and `filename-size` default to `0` to allow for easy tabulation.
example:
```
linux-lts-6.6_1 update x86_64 /home/abi/void/packages/hostdir/binpkgs/test 560
linux-lts-6.6_1 update x86_64 /home/abi/void/packages/hostdir/binpkgs/test 0 560
```
Fixes: #610

bin/xbps-install/transaction: print consistently for dry run

---

data/_xbps_src

many flags were missing, also updates for new flags:
- host arch (void-linux/void-packages#46263)
- verbose (void-linux/void-packages#48637)

data/_xbps_src: update completions

---

NEWS

- **NEWS: fix some typos/mispellings/grammar**
- **NEWS: fix indentation in new entries**
- **NEWS: add a few more changes**

NEWS updates

---

bin/xbps-checkvers/xbps-checkvers.1

By flexibeast:
- add EXAMPLES
By ericonr:
- trim down EXAMPLES
- clear up some sentences in general description
- improve text for some options

xbps-checkvers.1: improve options and general description

---

bin/xbps-alternatives/main.c
bin/xbps-create/main.c
bin/xbps-install/transaction.c
bin/xbps-rindex/index-add.c
bin/xbps-rindex/index-clean.c
doc/xbps_api_doxyfile.in
include/xbps.h.in
include/xbps/macro.h
include/xbps_api_impl.h
lib/log.c
lib/pkgdb.c
lib/plist.c
lib/transaction_check_conflicts.c
lib/transaction_check_replaces.c
lib/transaction_prepare.c
tests/xbps/libxbps/shell/replace_test.sh

This mostly reduces temporary allocations since they are easy to identify and fix.

Reduce allocations

---

lib/pkgdb.c

I found this typo when using xbps-install with insufficient permissions, and thought I'd open a PR for fixing it since it's a very minor issue.

Fixed typo on the permission check message.
